function fig_handle = Non_Dim_Energy_All(xaxis_name, xscale, yaxis_name, yscale,...
    vs, patch_lims, plot_curves, anno_string)
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here

fig_handle = figure('Position',[400,100,800,600]);

hold on
axes1 = gca;
axes1.XScale = xscale;
axes1.YScale = yscale;
xlabel(xaxis_name)
ylabel(yaxis_name)
lines = ["-", ":", ":", "--", ":", "--"];
colours = ['k', 'b', 'r', 'r', 'g', 'g'];
symbols = ['p', 'o', 'o', 's', 'o', 's'];
colours_cb = ["#27E0D8", "#648FFF", "#1D0C6B", "#DC267F", "#FE6100", ...
    "#FFB000", "#016D24"];
markersize = 2;
E_all_ana = [vs.E_all(1,:)./(vs.d_vals.^2*vs.kD);...
    vs.zeta./(1+vs.alpha_A_vals)*2*pi.*(1-cos(vs.phi_vals)).*vs.sigma_vals;...
    0.5*vs.alpha_A_vals.^2./(1+vs.alpha_A_vals)*2*pi.*(1-cos(vs.phi_vals)).*vs.sigma_vals;...
    0.5*vs.alpha_B_vals.^2./(1+vs.alpha_B_vals).*(1-pi*vs.sigma_vals.*sin(vs.phi_vals).^2);...
    4*pi*vs.kappa_vals./(vs.d_vals.^2*vs.kD).*(1-cos(vs.phi_vals));...
    pi/2*vs.alpha_B_vals.*vs.sigma_vals.*tan(vs.phi_vals).^2.*sin(vs.phi_vals).^2.*...
    (besselk(1,vs.R_vals./vs.lambda_vals.*sin(vs.phi_vals),1).^2-...
     besselk(0,vs.R_vals./vs.lambda_vals.*sin(vs.phi_vals),1).^2)./...
     besselk(1,vs.R_vals./vs.lambda_vals.*sin(vs.phi_vals),1).^2];
for ii=1:6
    plot(vs.param_1_vals, vs.E_all(ii,:)./(vs.d_vals.^2*vs.kD), ...
        strcat(colours(ii),lines(ii)))
    plot(vs.param_1_vals, E_all_ana(ii,:), ...
        strcat(colours(ii),symbols(ii)),'markersize', markersize,...
        'handlevisibility', 'off')
end
min_E = min(vs.E_all, [], 'all');
if min_E<0
    min_E = min_E*1.1;
else
    min_E = min_E*0.9;
end
max_E = max(vs.E_all, [], 'all')*1.1;
if numel(patch_lims) ~= 1
    small_param = patch_lims(1);
    large_param = patch_lims(2);
    patch([small_param, small_param, large_param, large_param],...
          [min_E, max_E, max_E, min_E], 'm', 'FaceAlpha', 0.05, ...
          'EdgeColor', 'None', 'HandleVisibility', 'off')
end
if numel(plot_curves) ~= 1
    plot_vert_lines(vs.param_1_vals(plot_curves), colours_cb)
end
names = {'$E_\mathrm{total}$','$E_\mathrm{adhesion}$',...
    '$E_\mathrm{stretch,A}$','$E_\mathrm{stretch,B}$',...
    '$E_\mathrm{bend,A}$','$E_\mathrm{bend,B}$'};
legend(names, 'Box','off',...
    'location', 'best')
annotation('textbox', [0.3,0.6,0.4,0.2], 'String',...
    anno_string,...
    'interpreter', 'latex','FontSize',16,...
    'FitBoxToText','on','LineStyle','none', 'Color','b')
xlim([vs.param_1_vals(1), vs.param_1_vals(end)])
end